//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viralme.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverDetail
    {
        public int DriverID { get; set; }
        public string DrivingStatistics { get; set; }
        public string Car { get; set; }
        public Nullable<System.Guid> AttachID { get; set; }
    }
}
