//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viralme.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGroup
    {
        public int GrpID { get; set; }
        public Nullable<int> PartID { get; set; }
        public string GrpName { get; set; }
        public Nullable<int> StatID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> root { get; set; }
        public Nullable<int> fatherID { get; set; }
        public Nullable<int> Removeable { get; set; }
    }
}
