//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viralme.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class viralmeEntities : DbContext
    {
        public viralmeEntities()
            : base("name=viralmeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<PublicRequest> PublicRequests { get; set; }
        public virtual DbSet<DriverDetail> DriverDetails { get; set; }
        public virtual DbSet<Campaign> Campaigns { get; set; }
    
        public virtual int DeleteDriverDetail(Nullable<int> driverID)
        {
            var driverIDParameter = driverID.HasValue ?
                new ObjectParameter("DriverID", driverID) :
                new ObjectParameter("DriverID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteDriverDetail", driverIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> InsertInDriverDetail(Nullable<int> driverID, string drivingStatistics, string car)
        {
            var driverIDParameter = driverID.HasValue ?
                new ObjectParameter("DriverID", driverID) :
                new ObjectParameter("DriverID", typeof(int));
    
            var drivingStatisticsParameter = drivingStatistics != null ?
                new ObjectParameter("DrivingStatistics", drivingStatistics) :
                new ObjectParameter("DrivingStatistics", typeof(string));
    
            var carParameter = car != null ?
                new ObjectParameter("Car", car) :
                new ObjectParameter("Car", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("InsertInDriverDetail", driverIDParameter, drivingStatisticsParameter, carParameter);
        }
    
        public virtual int UpdateDriverDetail(Nullable<int> driverID, string drivingStatistics, string car)
        {
            var driverIDParameter = driverID.HasValue ?
                new ObjectParameter("DriverID", driverID) :
                new ObjectParameter("DriverID", typeof(int));
    
            var drivingStatisticsParameter = drivingStatistics != null ?
                new ObjectParameter("DrivingStatistics", drivingStatistics) :
                new ObjectParameter("DrivingStatistics", typeof(string));
    
            var carParameter = car != null ?
                new ObjectParameter("Car", car) :
                new ObjectParameter("Car", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateDriverDetail", driverIDParameter, drivingStatisticsParameter, carParameter);
        }
    }
}
